### ISSUE TITLE
Detail with arg with enclosed quotes

### ISSUE THREAD

**Issue by dutrieux** [officiallysingh/spring-boot-problem-handler#4]
Hello,

If the message of detail have arg with enclosed quotes, the arg is not replace and quotes disappear.

For example :
` throw Problems.newInstance("building.alreadyExist").defaultDetail("The building with id '{0}' already exist").detailArgs(building.getId()).throwAble(HttpStatus.CONFLICT);`

![image](https://github.com/officiallysingh/spring-boot-problem-handler/assets/1622751/25c6aab0-c04c-4f4b-a8b2-9b41e289bf5d)

**Comment by officiallysingh** [comment]
It uses org.springframework.context.MessageSource to resolve placeholders in message template. The behaviour reported in this issue is as per design. In case you want to escape `'` you can set the message template as "The building with id ''{0}'' already exist" or you can set default detail as  "The building with id '{0}' already exist" and detailArgs as '<any value>' . Then the response would be as follows.

`{
  "type": "http://localhost:8080/problems/help.html#409",
  "title": "Conflict",
  "status": 409,
  "detail": "The building with id '123' already exist",
  "instance": "/problems/throw-problem",
  "method": "GET",
  "timestamp": "2024-02-13T17:22:13.666473+05:30",
  "code": "409"
}`

Please let me know in case of any other issues.
